[tool.poetry]
name = "mmqg"
version = "0.1.0"
description = ""
authors = ["Omar Zeghouani <omarzeghouanii@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <4.0"
transformers = "^4.35.2"
torch = [
  {version = "^2.1.0+cu118", source = "pytorch", markers = "sys_platform == 'linux'"},
  {version = "^2.1.0", source = "PyPI", markers = "sys_platform == 'darwin'"},
  {version = "^2.1.0", source = "PyPI", markers = "sys_platform == 'win32'"}
]
nltk = "^3.8.1"
sentencepiece = "^0.1.99"
summa = "^1.2.0"
keybert = "^0.8.3"

pymupdf = "^1.23.7"
spacy = "^3.7.2"
en-core-web-sm = {url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl"}
pydub = "^0.25.1"
accelerate = "^0.25.0"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu118"
priority = "explicit"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.6"
jupyter = "^1.0.0"
evaluate = "^0.4.1"
bert-score = "^0.3.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
