name: "Draft new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release.'
        required: true

jobs:
  draft-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.1.0
        with:
          version: ${{ github.event.inputs.version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Bump version in pyproject.toml
        run: poetry version ${{ github.event.inputs.version }}

      - name: Commit changelog and manifest
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Prepare release ${{ github.event.inputs.version }}
          branch: release/${{ github.event.inputs.version }}
          create_branch: true
          file_pattern: 'CHANGELOG.md pyproject.toml'

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ github.event.inputs.version }}
          base: master
          title: Release version ${{ github.event.inputs.version }}
          reviewers: ${{ github.actor }}
          body: |
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            I've updated the changelog and bumped the versions in the manifest files in this commit: ${{ steps.auto-commit-action.outputs.commit_hash }}.

            Merging this PR will create a GitHub release and upload any assets that are created as part of the release build.
